# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import match_pb2 as match__pb2


class MatchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Match = channel.unary_unary(
                '/match.Match/Match',
                request_serializer=match__pb2.MatchRequest.SerializeToString,
                response_deserializer=match__pb2.MatchResponse.FromString,
                )


class MatchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Match(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Match': grpc.unary_unary_rpc_method_handler(
                    servicer.Match,
                    request_deserializer=match__pb2.MatchRequest.FromString,
                    response_serializer=match__pb2.MatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'match.Match', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Match(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Match(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/match.Match/Match',
            match__pb2.MatchRequest.SerializeToString,
            match__pb2.MatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
